services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app # path mounted to update the container whenever a change to the source code is made.
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0